### ISSUE TITLE
as a user I should see the total amount in my cart as well as my orders

### ISSUE THREAD

**Issue by BethQ321** [Leading-Lady-Coders-LLC/2310-CapstoneProject#4]
- display total in cart- complete
- display total in orders- Complete

**Comment by kalasubramani** [comment]
- there is a function in /index.js - displayPrice() that formats the number to a decimal - This can be used here to display total price

**Comment by Green143** [comment]
- passed in price: product.price to pull price info from products to be calculated in the total order price*/
- added the total order price to be displayed for each order with the calculateLineItemTotal function
- added it under the showSearchResults and  productData to display the total order price.

**Comment by Green143** [comment]
add in the grand total for each order after the Order placed on
